version: "3.5"
services:
  mysql:
    image: mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tinee
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    restart: always
